name: Build and deploy Node.js project to Azure Function App - airtable-proxy-uf

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'airtable-proxy'
  NODE_VERSION: '20'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install
        working-directory: airtable-proxy

      - name: Build
        run: npm run build --if-present
        working-directory: airtable-proxy

      - name: Test
        run: npm run test --if-present
        working-directory: airtable-proxy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6C91678C9A6A492094BD8E17A9226434 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_22C3BBD6A2D5429482BB00568A67291A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_11D69C5B4DAF44D0A47D343BA1980285 }}

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        with:
          app-name: airtable-proxy-uf
          slot-name: Production
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
